name: structuraltextiles
favicon: null
layout_spectrum: 0.51906
typography_spectrum: 0.40132
title: structural textiles by Lorna Syson
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#401d39'
    - '#ffffff'
    - '#a08e9c'
    - '#cfc6cd'
    - '#70566b'
  brandStrength: 0.5625
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
