name: structuraltextiles
favicon: null
layout_spectrum: 0.49253
typography_spectrum: 0.40132
title: structural textiles by Lorna Syson
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f6f6f6'
    - '#b1d6de'
    - '#0a5d6b'
    - '#010204'
    - '#81b8c0'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
