name: structuraltextiles
favicon: null
layout_spectrum: 0.5789186200127006
typography_spectrum: 0.09614703548140824
title: structural textiles by Lorna Syson
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6649855170398951
  lightness: 0.5802778725046664
  saturation: 0.5680482161697
  rhythmicContrast: 0.901738244574517
purpose: []
