name: structuraltextiles
favicon: null
layout_spectrum: 0.42782
typography_spectrum: 0.86504
title: structural textiles by Lorna Syson
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#401d39'
    - '#ffffff'
    - '#a08e9c'
    - '#cfc6cd'
    - '#70566b'
  brandStrength: 0.6875
  lightness: 0.5802778725046664
  saturation: 0.5680482161697
  rhythmicContrast: 0.901738244574517
purpose: []
